name: Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-script:
    name: "[Cli] Build Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
  
  build-template:
    name: "[Template] Build Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template-path: ['vue-ts-element-plus', 'vue-ts-ant-design', 'vue-tsx-element-plus']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build Test
        working-directory: ./src/templates/${{ matrix.template-path }}
        run: |
          npm install
          npm run build

